<style>
    ul {list-style:none;}
    #drag { border: 3px solid black; padding:20px; width: 500px; margin: auto; display: inline-block;}
    #einput {width:400px;}
    #output {margin:20px;}

    #filesinput {
        visibility: collapse;
        width: 0px;
    }
    #output img{
        border: 2px solid #333;
        margin-right: 2px;
    }
    #small label {font-size:14px;}
    #small div {margin:5px 0;}
    #download {
            font-size: 16px;
    }
.jumbotron {
  padding-top: 15px;
  padding-bottom: 0px;
  text-align: center;
  font-size: 16px;
}
</style>


<div class="row">
  <div class="col-md-12">
    <h1>HTML5 Convertir Imagenes en Video</h1>
    <span id="status">Seleccciona algunas imagenes.</span><br><br>
  </div>
</div>

<div class="row">

  <div class="col-md-6">
    <div id="drag">Cargar Archivo:
        <button class="btn btn-default" id="fbutton">Selecciona archivo</button>
        <div id="small">

            <div class="form-group">
                <label for="width">Width:</label>
                <input class="form-control" id="width" type="number" step="1" value="500">
            </div>

            <div class="form-group">
                <label for="height">Height:</label>
                <input class="form-control" id="height" type="number" step="1" value="300">
            </div>

            <div class="form-group">
                <label for="framerate">Duración de Frames:</label>
                <input class="form-control" id="framerate" type="number" step="1" value="10">
            </div>

        </div>
        <button class="btn btn-success" id="createvideo">Create Video</button>

    </div>
    <input type="file" id="filesinput" multiple>
  </div>

  <div class="col-md-6">

    <div class="jumbotron">
        <video id="awesome" controls autoplay loop style="width: 450px;height: 270px;"></video>

        <a style="display:none" id="download" download="video.webm" >Descargar <em>Formato: WebM</em></a>

        <canvas id="canvas" style="display:none" style="width: 450px;height: 200px;"></canvas>
    </div>

  </div>

</div>


<script src="/js/custom.js"></script>
